# Generated by Django 5.1.1 on 2024-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='image',
        ),
    ]
