# Generated by Django 5.1.1 on 2024-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_remove_footballfield_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fields/'),
        ),
    ]
