# Generated by Django 5.1.1 on 2024-09-23 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_footballfield_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballfield',
            name='image',
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='field_images/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='football.footballfield')),
            ],
        ),
    ]
